# Generated by Django 3.2 on 2021-08-23 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=45)),
                ('nome_citacao', models.CharField(max_length=45)),
                ('id_CNPQ', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('campus', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('ano_conclusao', models.CharField(max_length=255)),
                ('curso_formacao', models.CharField(max_length=255)),
                ('faculdade_formacao', models.CharField(max_length=255)),
                ('vinculo_data_inicio', models.CharField(max_length=255)),
                ('tipo_vinculo', models.CharField(max_length=255)),
                ('outro_vinculo', models.CharField(max_length=255)),
                ('enquadramento', models.CharField(max_length=255)),
                ('outro_enquadramento', models.CharField(max_length=255)),
                ('src_image', models.ImageField(upload_to='pessoas')),
                ('last_update', models.CharField(max_length=255)),
                ('resumo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('informado_por', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('tipo_agrupador', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('id_curriculo', models.CharField(max_length=50)),
                ('ano_inicio', models.CharField(max_length=4)),
                ('situacao', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('coordenador', models.CharField(max_length=50)),
                ('informado_por', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SetorAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=45)),
                ('producao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores_atividade', to='lattes.producao')),
            ],
        ),
        migrations.CreateModel(
            name='ProducaoAutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_autoria', models.CharField(max_length=45)),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Autores', to='lattes.autor')),
                ('producao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoes', to='lattes.producao')),
            ],
        ),
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=45)),
                ('producao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palavrasChave', to='lattes.producao')),
            ],
        ),
        migrations.CreateModel(
            name='AreaConhecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grande_area', models.CharField(max_length=45)),
                ('area', models.CharField(max_length=45)),
                ('sub_area', models.CharField(max_length=45)),
                ('especialidade', models.CharField(max_length=45)),
                ('producao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_conhecimento', to='lattes.producao')),
            ],
        ),
    ]
